# Generated by Django 3.2.25 on 2024-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_your_username', models.CharField(max_length=50)),
                ('enter_the_username_you_want_to_request_from', models.CharField(max_length=50)),
                ('enter_amount_to_request', models.IntegerField()),
            ],
        ),
    ]
