# Generated by Django 3.2.25 on 2024-04-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_currencyrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='name',
            new_name='user',
        ),
    ]
