# Generated by Django 3.2.25 on 2024-04-23 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payapp', '0003_rename_name_currency_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to=settings.AUTH_USER_MODEL),
        ),
    ]
