# Generated by Django 3.2.25 on 2024-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_alter_currency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('GBP', 'Great British Pounds'), ('EUR', 'Euros')], default='GBP', max_length=3),
        ),
    ]
