# Generated by Django 3.2.25 on 2024-04-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_currency_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'US Dollars'), ('GBP', 'Great British Pounds'), ('EUR', 'Euros')], max_length=3),
        ),
    ]
