# Generated by Django 3.2.25 on 2024-04-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_alter_currency_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('GBP', 'Great British Pounds'), ('USD', 'US Dollars'), ('EUR', 'Euros')], default='GBP', max_length=3),
        ),
    ]
