# Generated by Django 3.2.25 on 2024-04-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_alter_currency_currency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='transferAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('transfer_amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
